//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthWind.BlazingPizza.Frontend.RazorViews.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NorthWind.BlazingPizza.Frontend.RazorViews.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Complementos adicionales.
        /// </summary>
        internal static string AdditionalToppingsLabel {
            get {
                return ResourceManager.GetString("AdditionalToppingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ciudad.
        /// </summary>
        internal static string AddressCityLabel {
            get {
                return ResourceManager.GetString("AddressCityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección.
        /// </summary>
        internal static string AddressLine1Label {
            get {
                return ResourceManager.GetString("AddressLine1Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Colonia.
        /// </summary>
        internal static string AddressLine2 {
            get {
                return ResourceManager.GetString("AddressLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string AddressNameLabel {
            get {
                return ResourceManager.GetString("AddressNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código Postal.
        /// </summary>
        internal static string AddressPostalCode {
            get {
                return ResourceManager.GetString("AddressPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        internal static string AddressRegionLabel {
            get {
                return ResourceManager.GetString("AddressRegionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar a ....
        /// </summary>
        internal static string AddressTitleLabel {
            get {
                return ResourceManager.GetString("AddressTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blazing Pizza.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ordenar &gt;.
        /// </summary>
        internal static string CheckoutLinkText {
            get {
                return ResourceManager.GetString("CheckoutLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elegir pizza.
        /// </summary>
        internal static string ChoosePizzaLinkText {
            get {
                return ResourceManager.GetString("ChoosePizzaLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pedido realizado.
        /// </summary>
        internal static string CreatedOrderTimeText {
            get {
                return ResourceManager.GetString("CreatedOrderTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tamaño.
        /// </summary>
        internal static string CustomPizzaSizeLabel {
            get {
                return ResourceManager.GetString("CustomPizzaSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha realizado alguna orden.
        /// </summary>
        internal static string EmptyOrdersText {
            get {
                return ResourceManager.GetString("EmptyOrdersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a maximo alcanzado.
        /// </summary>
        internal static string HasMaximumToppingsText {
            get {
                return ResourceManager.GetString("HasMaximumToppingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elnombre, dirección ycódigo postal son requeridos.
        /// </summary>
        internal static string InvalidAddressText {
            get {
                return ResourceManager.GetString("InvalidAddressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargando....
        /// </summary>
        internal static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis órdenes.
        /// </summary>
        internal static string MyOrdersText {
            get {
                return ResourceManager.GetString("MyOrdersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo sentimos, pero esta orden no existe..
        /// </summary>
        internal static string NotFoundOrderDetailText {
            get {
                return ResourceManager.GetString("NotFoundOrderDetailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a !Orden no encontrada!.
        /// </summary>
        internal static string NotFoundOrderText {
            get {
                return ResourceManager.GetString("NotFoundOrderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ordena alguna pizza.
        /// </summary>
        internal static string OrderAnyPizzaText {
            get {
                return ResourceManager.GetString("OrderAnyPizzaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ordenar.
        /// </summary>
        internal static string OrderButtonText {
            get {
                return ResourceManager.GetString("OrderButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pizzas:.
        /// </summary>
        internal static string PizzasText {
            get {
                return ResourceManager.GetString("PizzasText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realizar pedido.
        /// </summary>
        internal static string PlaceOrderButtonText {
            get {
                return ResourceManager.GetString("PlaceOrderButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio.
        /// </summary>
        internal static string PriceText {
            get {
                return ResourceManager.GetString("PriceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo lamentamos, no existe nada en esta dirección..
        /// </summary>
        internal static string ResourceNotFoundErrorMessage {
            get {
                return ResourceManager.GetString("ResourceNotFoundErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recurso no encontrado.
        /// </summary>
        internal static string ResourceNotFoundPageTitle {
            get {
                return ResourceManager.GetString("ResourceNotFoundPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Revisar la orden.
        /// </summary>
        internal static string ReviewOrderText {
            get {
                return ResourceManager.GetString("ReviewOrderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione una pizza para empezar.
        /// </summary>
        internal static string SelectPizzaText {
            get {
                return ResourceManager.GetString("SelectPizzaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona.
        /// </summary>
        internal static string SelectToppingOptionText {
            get {
                return ResourceManager.GetString("SelectToppingOptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado:.
        /// </summary>
        internal static string StatusText {
            get {
                return ResourceManager.GetString("StatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio total:.
        /// </summary>
        internal static string TotalPriceText {
            get {
                return ResourceManager.GetString("TotalPriceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total.
        /// </summary>
        internal static string TotalText {
            get {
                return ResourceManager.GetString("TotalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rastrear &gt;.
        /// </summary>
        internal static string TrackText {
            get {
                return ResourceManager.GetString("TrackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu Pedido.
        /// </summary>
        internal static string YourOrderText {
            get {
                return ResourceManager.GetString("YourOrderText", resourceCulture);
            }
        }
    }
}
