//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthWind.BlazingPizza.Entities.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NorthWind.BlazingPizza.Entities.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe proporcionar un máximo de 50 caracteres de la ciudad..
        /// </summary>
        internal static string AddressCityMaximumLengthRequiredErrorMessage {
            get {
                return ResourceManager.GetString("AddressCityMaximumLengthRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe proporcionar al menos 3 caracteres de la ciudad..
        /// </summary>
        internal static string AddressCityMinimumLengthRequiredErrorMessage {
            get {
                return ResourceManager.GetString("AddressCityMinimumLengthRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La ciudad es requerida..
        /// </summary>
        internal static string AddressCityRequiredErrorMessage {
            get {
                return ResourceManager.GetString("AddressCityRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe proporcionar un máximo de 100 caracteres del nombre..
        /// </summary>
        internal static string AddressLine1MaximumLenghtRequiredErrorMessage {
            get {
                return ResourceManager.GetString("AddressLine1MaximumLenghtRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe proporcionar al menos 5 caracteres de la línea 1..
        /// </summary>
        internal static string AddressLine1MinimummLenghtRequiredErrorMessage {
            get {
                return ResourceManager.GetString("AddressLine1MinimummLenghtRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El línea 1 es requerida..
        /// </summary>
        internal static string AddressLine1RequiredErrorMessage {
            get {
                return ResourceManager.GetString("AddressLine1RequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe proporcionar un máximo de 100 caracteres del nombre..
        /// </summary>
        internal static string AddressLine2MaximumLenghtRequiredErrorMessage {
            get {
                return ResourceManager.GetString("AddressLine2MaximumLenghtRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe proporcionar un máximo de 100 caracteres del nombre..
        /// </summary>
        internal static string AddressNameMaximumLengthRequiredErrorMessage {
            get {
                return ResourceManager.GetString("AddressNameMaximumLengthRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe proporcionar al menos 3 caracteres del nombre..
        /// </summary>
        internal static string AddressNameMinimumLengthRequiredErrorMessage {
            get {
                return ResourceManager.GetString("AddressNameMinimumLengthRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre es requerido..
        /// </summary>
        internal static string AddressNameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("AddressNameRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proporcione 5 dígitos del código postal..
        /// </summary>
        internal static string AddressPostalCodeInvalidErrorMessage {
            get {
                return ResourceManager.GetString("AddressPostalCodeInvalidErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código postal es requerido..
        /// </summary>
        internal static string AddressPostalCodeRequiredErrorMessage {
            get {
                return ResourceManager.GetString("AddressPostalCodeRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe proporcionar un máximo de 20 caracteres de la región..
        /// </summary>
        internal static string AddressRegionMaximumLengthRequiredErrorMessage {
            get {
                return ResourceManager.GetString("AddressRegionMaximumLengthRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe proporcionar al menos 3 caracteres de la región..
        /// </summary>
        internal static string AddressRegionMinimumLengthRequiredErrorMessage {
            get {
                return ResourceManager.GetString("AddressRegionMinimumLengthRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La región es requerida..
        /// </summary>
        internal static string AddressRegionRequiredErrorMessage {
            get {
                return ResourceManager.GetString("AddressRegionRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entregado.
        /// </summary>
        internal static string DeliveredText {
            get {
                return ResourceManager.GetString("DeliveredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En camino.
        /// </summary>
        internal static string OutForDeliveryText {
            get {
                return ResourceManager.GetString("OutForDeliveryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preparando.
        /// </summary>
        internal static string PreparingText {
            get {
                return ResourceManager.GetString("PreparingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desconocido.
        /// </summary>
        internal static string UnknownStatusText {
            get {
                return ResourceManager.GetString("UnknownStatusText", resourceCulture);
            }
        }
    }
}
