//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using Microsoft.AspNetCore.Components;
using Microsoft.Extensions.Options;
using NorthWind.BlazingPizza.Frontend.BusinessObjects.Agregates;
using NorthWind.BlazingPizza.Frontend.BusinessObjects.Options;
using NorthWind.BlazingPizza.Frontend.ViewModels.ConfigurePizzaDialog;


namespace NorthWind.BlazingPizza.Frontend.RazorViews.Components
{
	public partial class ConfigurePizzaDialog
	{
		[Inject]
		ConfigurePizzaDialogViewModel ViewModel { get; set; }
		[Inject]
		IOptions<BlazingPizzaOptions> Options { get; set; }
		[Parameter]
		public CustomPizza CustomPizza { get; set; }
		[Parameter]
		public EventCallback OnCancel { get; set; } //llamada de regreso
		[Parameter]
		public EventCallback OnConfirm { get; set; }

		protected override async Task OnInitializedAsync()
		{
			await ViewModel.GetToppingsAsync();
		}
	}
}