// <autogenerated />
using Microsoft.AspNetCore.Components;
using NorthWind.BlazingPizza.Entities.Dtos.GetSpecials;
using NorthWind.BlazingPizza.Frontend.ViewModels.GetSpecials;

namespace NorthWind.BlazingPizza.Frontend.RazorViews.Components
{
	//las dependencias se reciben a taves del atributo o directiva @Inject no del constructor
	public partial class Specials/*: ComponentBase*/ // es opcional colocarlo ya que internamente lo coloca aunque no se vea
	{
	//la vista no habla con el modelo, si no con el viewModel, pr ello se debe hacer una instancia del viewmodel
		//De esta forma recibo la dependencia, indicandole que se va a injectar del viewmodl
		[Inject]
	 GetSpecialsViewModel ViewModel { get; set; }

		//notificar a nuestro padre conun evento
		[Parameter]
		public EventCallback<PizzaSpecialDto> OnClickSpecial {  get; set; }

		//ideal para ir por los datos
		//el override cuando el componente se incializa(omponenete, etc)
		override protected async Task OnInitializedAsync()
		{
			await ViewModel.GetSpecialsAsync();
		}
	}
}

//tradicionalmente recibimos a travez del cnsructor las dependencias
	//pero en el caso de los componentes razor.cs, no se reciben asi
	//si no a travez del atributo
		//Inject