// <autogenerated />
using Microsoft.AspNetCore.Components;
using NorthWind.BlazingPizza.Frontend.ViewModels.GetSpecials;

namespace NorthWind.BlazingPizza.Frontend.RazorViews.Components
{
	//las dependencias se reciben a taves del atributo o directiva @Inject no del constructor
	public partial class Specials
	{
		//De esta forma recibo la dependencia, indicandole que se va a injectar del viewmodl
		[Inject]
	 GetSpecialsViewModel ViewModel { get; set; }

		//ideal para ir por los datos
		//el override cuando el componente se incializa(omponenete, etc)
		override protected async Task OnInitializedAsync()
		{
			await ViewModel.GetSpecialsAsync();
		}
	}
}